### ISSUE TITLE
Fatal error: invalid distance too far back

### ISSUE THREAD

**Issue by kirillkostko** [RealFaviconGenerator/grunt-real-favicon#31]
From time to rime I receive that error
```Fatal error: invalid distance too far back```

**Comment by martinmethod** [comment]
+1

**Comment by tylerneu** [comment]
I have reproduced the same error using `cli-real-favicon` as well.

**Comment by phbernard** [comment]
Just a short message to notify that I saw this issue and that I will investigate it next week. I have no idea what's happening.

**Comment by phbernard** [comment]
Just a small note to indicate that this issue might have a fix that needs to be tested... by people who actually observe it (it works on my side). If you are willing to spend a few minutes, [there's a procedure](https://github.com/RealFaviconGenerator/grunt-real-favicon/issues/32#issuecomment-244340355).

**Comment by kirillkostko** [comment]
Hi @phbernard ,

Sorry for the delay. I've tested via instruction. The error appears and looks the same for both versions 0.1.7 and 0.2.0.

```
$ npm test

> rfg-api@0.2.0 test C:\test\rfg-api
> mocha



  Change log
    #changeLog()
      √ should return changes since a certain versions (96ms)
      √ should return all changes (48ms)

  RFG Api
    #fileToBase64()
      √ should return the content of a file encoded in base64
      √ should return an error when the file does not exist
    #fileToBase64Sync()
      √ should return the content of a file encoded in base64
    #generateFavicon()
      √ should generate a favicon (7112ms)
      √ should generate a favicon based on an SVG image (6719ms)
    #injectFaviconMarkups()
      1) should inject favicon code
      2) should remove existing markups
      3) should inject extra markups
      4) should remove extra markups
      5) should keep extra markups
    #camelCaseToUnderscore()
      √ should turn camel case to underscores
    #camelCaseToUnderscoreRequest()
      √ should convert a JS request (camelcase) to an RFG request (underscore)

  Request helpers
    #escapeJSONSpecialChars()
      √ should escape special characters
    #isUrl()
      √ should set path and URL apart
    #normalizeMasterPicture()
      √ should inline file content when necessary
    #normalizeAllMasterPictures()
      √ should inline all master pictures of a request
    #createRequest()
      √ should generate a RFG API request without settings or versioning
      √ should generate a RFG API request with settings or versioning


  15 passing (14s)
  5 failing

  1) RFG Api #injectFaviconMarkups() should inject favicon code:

      AssertionError: '<html>\r  <head>\r    <title>Test Document</title>\r    <meta name="description" content="Testing doc for rfg-api">\r  <link re == '<html>\r\n  <head>\r\n    <title>Test Document</title>\r\n    <meta name="description" content="Testing doc for rfg-api">\r\n
      + expected - actual

  <link rel="icon" type="image/png" href="favicons/favicon-192x192.png" sizes="192x192"><link rel="icon" type="image/png" href="favicons/favicon-160x160.png" si</html>y>ey!</h1>ead>
      +<html>
      +  <head>
      +    <title>Test Document</title>
      +    <meta name="description" content="Testing doc for rfg-api">
      +  <link rel="icon" type="image/png" href="favicons/favicon-192x192.png" sizes="192x192"><link rel="icon" type="image/png" href="favicons/favicon-160x160.png" sizes="160x160"></head>
      +  <body>
      +    <h1>Hey!</h1>
      +  </body>
      +</html>

      at C:\test\rfg-api\test\test.js:146:16
      at Object.metaparser.callback (C:\test\rfg-api\index.js:116:16)
      at C:\test\rfg-api\node_modules\metaparser\index.js:78:32
      at C:\test\rfg-api\node_modules\async\dist\async.js:486:20
      at nextTask (C:\test\rfg-api\node_modules\async\dist\async.js:5008:33)
      at C:\test\rfg-api\node_modules\async\dist\async.js:5015:17
      at C:\test\rfg-api\node_modules\async\dist\async.js:339:31
      at C:\test\rfg-api\node_modules\async\dist\async.js:847:20
      at C:\test\rfg-api\node_modules\metaparser\index.js:73:21
      at nextTask (C:\test\rfg-api\node_modules\async\dist\async.js:5021:18)
      at C:\test\rfg-api\node_modules\async\dist\async.js:5015:17
      at C:\test\rfg-api\node_modules\async\dist\async.js:339:31
      at C:\test\rfg-api\node_modules\async\dist\async.js:847:20
      at C:\test\rfg-api\node_modules\metaparser\index.js:56:21
      at nextTask (C:\test\rfg-api\node_modules\async\dist\async.js:5021:18)
      at C:\test\rfg-api\node_modules\async\dist\async.js:5015:17
      at C:\test\rfg-api\node_modules\async\dist\async.js:339:31
      at C:\test\rfg-api\node_modules\async\dist\async.js:847:20
      at C:\test\rfg-api\node_modules\metaparser\index.js:45:21
      at nextTask (C:\test\rfg-api\node_modules\async\dist\async.js:5021:18)
      at C:\test\rfg-api\node_modules\async\dist\async.js:5015:17
      at C:\test\rfg-api\node_modules\async\dist\async.js:339:31
      at C:\test\rfg-api\node_modules\async\dist\async.js:847:20
      at decodeData (C:\test\rfg-api\node_modules\metaparser\index.js:30:17)
      at C:\test\rfg-api\node_modules\metaparser\index.js:37:17
      at nextTask (C:\test\rfg-api\node_modules\async\dist\async.js:5021:18)
      at Object.waterfall (C:\test\rfg-api\node_modules\async\dist\async.js:5024:9)
      at module.exports (C:\test\rfg-api\node_modules\metaparser\index.js:24:15)
      at Object.exports.injectFaviconMarkups (C:\test\rfg-api\index.js:111:5)
      at Context.<anonymous> (C:\test\rfg-api\test\test.js:144:11)
      at callFnAsync (C:\test\rfg-api\node_modules\mocha\lib\runnable.js:349:8)
      at Test.Runnable.run (C:\test\rfg-api\node_modules\mocha\lib\runnable.js:301:7)
      at Runner.runTest (C:\test\rfg-api\node_modules\mocha\lib\runner.js:422:10)
      at C:\test\rfg-api\node_modules\mocha\lib\runner.js:528:12
      at next (C:\test\rfg-api\node_modules\mocha\lib\runner.js:342:14)
      at C:\test\rfg-api\node_modules\mocha\lib\runner.js:352:7
      at next (C:\test\rfg-api\node_modules\mocha\lib\runner.js:284:14)
      at Immediate.<anonymous> (C:\test\rfg-api\node_modules\mocha\lib\runner.js:320:5)

  2) RFG Api #injectFaviconMarkups() should remove existing markups:

      AssertionError: '<html>\r  <head>\r    <title>Test Document</title>\r    <meta name="description" content="Testing doc for rfg-api">\r  <link re == '<html>\r\n  <head>\r\n    <title>Test Document</title>\r\n    <meta name="description" content="Testing doc for rfg-api">\r\n
      + expected - actual

  <link rel="icon" type="image/png" href="favicons/favicon-192x192.png" sizes="192x192"><link rel="icon" type="image/png" href="favicons/favicon-160x160.png" si</html>y>ey!</h1>ead>
      +<html>
      +  <head>
      +    <title>Test Document</title>
      +    <meta name="description" content="Testing doc for rfg-api">
      +  <link rel="icon" type="image/png" href="favicons/favicon-192x192.png" sizes="192x192"><link rel="icon" type="image/png" href="favicons/favicon-160x160.png" sizes="160x160"></head>
      +  <body>
      +    <h1>Hey!</h1>
      +  </body>
      +</html>

      at C:\test\rfg-api\test\test.js:160:16
      at Object.metaparser.callback (C:\test\rfg-api\index.js:116:16)
      at C:\test\rfg-api\node_modules\metaparser\index.js:78:32
      at C:\test\rfg-api\node_modules\async\dist\async.js:486:20
      at nextTask (C:\test\rfg-api\node_modules\async\dist\async.js:5008:33)
      at C:\test\rfg-api\node_modules\async\dist\async.js:5015:17
      at C:\test\rfg-api\node_modules\async\dist\async.js:339:31
      at C:\test\rfg-api\node_modules\async\dist\async.js:847:20
      at C:\test\rfg-api\node_modules\metaparser\index.js:73:21
      at nextTask (C:\test\rfg-api\node_modules\async\dist\async.js:5021:18)
      at C:\test\rfg-api\node_modules\async\dist\async.js:5015:17
      at C:\test\rfg-api\node_modules\async\dist\async.js:339:31
      at C:\test\rfg-api\node_modules\async\dist\async.js:847:20
      at C:\test\rfg-api\node_modules\metaparser\index.js:56:21
      at nextTask (C:\test\rfg-api\node_modules\async\dist\async.js:5021:18)
      at C:\test\rfg-api\node_modules\async\dist\async.js:5015:17
      at C:\test\rfg-api\node_modules\async\dist\async.js:339:31
      at C:\test\rfg-api\node_modules\async\dist\async.js:847:20
      at C:\test\rfg-api\node_modules\metaparser\index.js:45:21
      at nextTask (C:\test\rfg-api\node_modules\async\dist\async.js:5021:18)
      at C:\test\rfg-api\node_modules\async\dist\async.js:5015:17
      at C:\test\rfg-api\node_modules\async\dist\async.js:339:31
      at C:\test\rfg-api\node_modules\async\dist\async.js:847:20
      at decodeData (C:\test\rfg-api\node_modules\metaparser\index.js:30:17)
      at C:\test\rfg-api\node_modules\metaparser\index.js:37:17
      at nextTask (C:\test\rfg-api\node_modules\async\dist\async.js:5021:18)
      at Object.waterfall (C:\test\rfg-api\node_modules\async\dist\async.js:5024:9)
      at module.exports (C:\test\rfg-api\node_modules\metaparser\index.js:24:15)
      at Object.exports.injectFaviconMarkups (C:\test\rfg-api\index.js:111:5)
      at Context.<anonymous> (C:\test\rfg-api\test\test.js:158:11)
      at callFnAsync (C:\test\rfg-api\node_modules\mocha\lib\runnable.js:349:8)
      at Test.Runnable.run (C:\test\rfg-api\node_modules\mocha\lib\runnable.js:301:7)
      at Runner.runTest (C:\test\rfg-api\node_modules\mocha\lib\runner.js:422:10)
      at C:\test\rfg-api\node_modules\mocha\lib\runner.js:528:12
      at next (C:\test\rfg-api\node_modules\mocha\lib\runner.js:342:14)
      at C:\test\rfg-api\node_modules\mocha\lib\runner.js:352:7
      at next (C:\test\rfg-api\node_modules\mocha\lib\runner.js:284:14)
      at Immediate.<anonymous> (C:\test\rfg-api\node_modules\mocha\lib\runner.js:320:5)

  3) RFG Api #injectFaviconMarkups() should inject extra markups:

      AssertionError: '<html>\r  <head>\r    <title>Test Document</title>\r    <meta name="description" content="Testing doc for rfg-api">\r  <link re == '<html>\r\n  <head>\r\n    <title>Test Document</title>\r\n    <meta name="description" content="Testing doc for rfg-api">\r\n
      + expected - actual

  <link rel="icon" type="image/png" href="favicons/favicon-192x192.png" sizes="192x192"><link rel="icon" type="image/png" href="favicons/favicon-160x160.png" si</html>y>ey!</h1>nk content="an extra markup"></head>
      +<html>
      +  <head>
      +    <title>Test Document</title>
      +    <meta name="description" content="Testing doc for rfg-api">
      +  <link rel="icon" type="image/png" href="favicons/favicon-192x192.png" sizes="192x192"><link rel="icon" type="image/png" href="favicons/favicon-160x160.png" sizes="160x160"><link content="an extra markup"></head>
      +  <body>
      +    <h1>Hey!</h1>
      +  </body>
      +</html>

      at C:\test\rfg-api\test\test.js:176:16
      at Object.metaparser.callback (C:\test\rfg-api\index.js:116:16)
      at C:\test\rfg-api\node_modules\metaparser\index.js:78:32
      at C:\test\rfg-api\node_modules\async\dist\async.js:486:20
      at nextTask (C:\test\rfg-api\node_modules\async\dist\async.js:5008:33)
      at C:\test\rfg-api\node_modules\async\dist\async.js:5015:17
      at C:\test\rfg-api\node_modules\async\dist\async.js:339:31
      at C:\test\rfg-api\node_modules\async\dist\async.js:847:20
      at C:\test\rfg-api\node_modules\metaparser\index.js:73:21
      at nextTask (C:\test\rfg-api\node_modules\async\dist\async.js:5021:18)
      at C:\test\rfg-api\node_modules\async\dist\async.js:5015:17
      at C:\test\rfg-api\node_modules\async\dist\async.js:339:31
      at C:\test\rfg-api\node_modules\async\dist\async.js:847:20
      at C:\test\rfg-api\node_modules\metaparser\index.js:56:21
      at nextTask (C:\test\rfg-api\node_modules\async\dist\async.js:5021:18)
      at C:\test\rfg-api\node_modules\async\dist\async.js:5015:17
      at C:\test\rfg-api\node_modules\async\dist\async.js:339:31
      at C:\test\rfg-api\node_modules\async\dist\async.js:847:20
      at C:\test\rfg-api\node_modules\metaparser\index.js:45:21
      at nextTask (C:\test\rfg-api\node_modules\async\dist\async.js:5021:18)
      at C:\test\rfg-api\node_modules\async\dist\async.js:5015:17
      at C:\test\rfg-api\node_modules\async\dist\async.js:339:31
      at C:\test\rfg-api\node_modules\async\dist\async.js:847:20
      at decodeData (C:\test\rfg-api\node_modules\metaparser\index.js:30:17)
      at C:\test\rfg-api\node_modules\metaparser\index.js:37:17
      at nextTask (C:\test\rfg-api\node_modules\async\dist\async.js:5021:18)
      at Object.waterfall (C:\test\rfg-api\node_modules\async\dist\async.js:5024:9)
      at module.exports (C:\test\rfg-api\node_modules\metaparser\index.js:24:15)
      at Object.exports.injectFaviconMarkups (C:\test\rfg-api\index.js:111:5)
      at Context.<anonymous> (C:\test\rfg-api\test\test.js:172:11)
      at callFnAsync (C:\test\rfg-api\node_modules\mocha\lib\runnable.js:349:8)
      at Test.Runnable.run (C:\test\rfg-api\node_modules\mocha\lib\runnable.js:301:7)
      at Runner.runTest (C:\test\rfg-api\node_modules\mocha\lib\runner.js:422:10)
      at C:\test\rfg-api\node_modules\mocha\lib\runner.js:528:12
      at next (C:\test\rfg-api\node_modules\mocha\lib\runner.js:342:14)
      at C:\test\rfg-api\node_modules\mocha\lib\runner.js:352:7
      at next (C:\test\rfg-api\node_modules\mocha\lib\runner.js:284:14)
      at Immediate.<anonymous> (C:\test\rfg-api\node_modules\mocha\lib\runner.js:320:5)

  4) RFG Api #injectFaviconMarkups() should remove extra markups:

      AssertionError: '<html>\r  <head>\r    <title>Test Document</title>\r  <link rel="icon" type="image/png" href="favicons/favicon-192x192.png" siz == '<html>\r\n  <head>\r\n    <title>Test Document</title>\r\n  <link rel="icon" type="image/png" href="favicons/favicon-192x192.pn
      + expected - actual

  <link rel="icon" type="image/png" href="favicons/favicon-192x192.png" sizes="192x192"><link rel="icon" type="image/png" href="favicons/favicon-160x160.png" si</html>y>ey!</h1>ead>
      +<html>
      +  <head>
      +    <title>Test Document</title>
      +  <link rel="icon" type="image/png" href="favicons/favicon-192x192.png" sizes="192x192"><link rel="icon" type="image/png" href="favicons/favicon-160x160.png" sizes="160x160"></head>
      +  <body>
      +    <h1>Hey!</h1>
      +  </body>
      +</html>

      at C:\test\rfg-api\test\test.js:192:16
      at Object.metaparser.callback (C:\test\rfg-api\index.js:116:16)
      at C:\test\rfg-api\node_modules\metaparser\index.js:78:32
      at C:\test\rfg-api\node_modules\async\dist\async.js:486:20
      at nextTask (C:\test\rfg-api\node_modules\async\dist\async.js:5008:33)
      at C:\test\rfg-api\node_modules\async\dist\async.js:5015:17
      at C:\test\rfg-api\node_modules\async\dist\async.js:339:31
      at C:\test\rfg-api\node_modules\async\dist\async.js:847:20
      at C:\test\rfg-api\node_modules\metaparser\index.js:73:21
      at nextTask (C:\test\rfg-api\node_modules\async\dist\async.js:5021:18)
      at C:\test\rfg-api\node_modules\async\dist\async.js:5015:17
      at C:\test\rfg-api\node_modules\async\dist\async.js:339:31
      at C:\test\rfg-api\node_modules\async\dist\async.js:847:20
      at C:\test\rfg-api\node_modules\metaparser\index.js:56:21
      at nextTask (C:\test\rfg-api\node_modules\async\dist\async.js:5021:18)
      at C:\test\rfg-api\node_modules\async\dist\async.js:5015:17
      at C:\test\rfg-api\node_modules\async\dist\async.js:339:31
      at C:\test\rfg-api\node_modules\async\dist\async.js:847:20
      at C:\test\rfg-api\node_modules\metaparser\index.js:45:21
      at nextTask (C:\test\rfg-api\node_modules\async\dist\async.js:5021:18)
      at C:\test\rfg-api\node_modules\async\dist\async.js:5015:17
      at C:\test\rfg-api\node_modules\async\dist\async.js:339:31
      at C:\test\rfg-api\node_modules\async\dist\async.js:847:20
      at decodeData (C:\test\rfg-api\node_modules\metaparser\index.js:30:17)
      at C:\test\rfg-api\node_modules\metaparser\index.js:37:17
      at nextTask (C:\test\rfg-api\node_modules\async\dist\async.js:5021:18)
      at Object.waterfall (C:\test\rfg-api\node_modules\async\dist\async.js:5024:9)
      at module.exports (C:\test\rfg-api\node_modules\metaparser\index.js:24:15)
      at Object.exports.injectFaviconMarkups (C:\test\rfg-api\index.js:111:5)
      at Context.<anonymous> (C:\test\rfg-api\test\test.js:188:11)
      at callFnAsync (C:\test\rfg-api\node_modules\mocha\lib\runnable.js:349:8)
      at Test.Runnable.run (C:\test\rfg-api\node_modules\mocha\lib\runnable.js:301:7)
      at Runner.runTest (C:\test\rfg-api\node_modules\mocha\lib\runner.js:422:10)
      at C:\test\rfg-api\node_modules\mocha\lib\runner.js:528:12
      at next (C:\test\rfg-api\node_modules\mocha\lib\runner.js:342:14)
      at C:\test\rfg-api\node_modules\mocha\lib\runner.js:352:7
      at next (C:\test\rfg-api\node_modules\mocha\lib\runner.js:284:14)
      at Immediate.<anonymous> (C:\test\rfg-api\node_modules\mocha\lib\runner.js:320:5)

  5) RFG Api #injectFaviconMarkups() should keep extra markups:

      AssertionError: '<html>\r  <head>\r    <title>Test Document</title>\r    <meta name="description" content="Testing doc for rfg-api">\r    <link  == '<html>\r\n  <head>\r\n    <title>Test Document</title>\r\n    <meta name="description" content="Testing doc for rfg-api">\r\n
      + expected - actual

  <link rel="icon" type="image/png" href="favicons/favicon-192x192.png" sizes="192x192"><link rel="icon" type="image/png" href="favicons/favicon-160x160.png" si</html>y>ey!</h1>ead>
      +<html>
      +  <head>
      +    <title>Test Document</title>
      +    <meta name="description" content="Testing doc for rfg-api">
      +    <link rel="icon" type="image/png" href="somepic.png" sizes="32x32">
      +  <link rel="icon" type="image/png" href="favicons/favicon-192x192.png" sizes="192x192"><link rel="icon" type="image/png" href="favicons/favicon-160x160.png" sizes="160x160"></head>
      +  <body>
      +    <h1>Hey!</h1>
      +  </body>
      +</html>

      at C:\test\rfg-api\test\test.js:208:16
      at Object.metaparser.callback (C:\test\rfg-api\index.js:116:16)
      at C:\test\rfg-api\node_modules\metaparser\index.js:78:32
      at C:\test\rfg-api\node_modules\async\dist\async.js:486:20
      at nextTask (C:\test\rfg-api\node_modules\async\dist\async.js:5008:33)
      at C:\test\rfg-api\node_modules\async\dist\async.js:5015:17
      at C:\test\rfg-api\node_modules\async\dist\async.js:339:31
      at C:\test\rfg-api\node_modules\async\dist\async.js:847:20
      at C:\test\rfg-api\node_modules\metaparser\index.js:73:21
      at nextTask (C:\test\rfg-api\node_modules\async\dist\async.js:5021:18)
      at C:\test\rfg-api\node_modules\async\dist\async.js:5015:17
      at C:\test\rfg-api\node_modules\async\dist\async.js:339:31
      at C:\test\rfg-api\node_modules\async\dist\async.js:847:20
      at C:\test\rfg-api\node_modules\metaparser\index.js:56:21
      at nextTask (C:\test\rfg-api\node_modules\async\dist\async.js:5021:18)
      at C:\test\rfg-api\node_modules\async\dist\async.js:5015:17
      at C:\test\rfg-api\node_modules\async\dist\async.js:339:31
      at C:\test\rfg-api\node_modules\async\dist\async.js:847:20
      at C:\test\rfg-api\node_modules\metaparser\index.js:45:21
      at nextTask (C:\test\rfg-api\node_modules\async\dist\async.js:5021:18)
      at C:\test\rfg-api\node_modules\async\dist\async.js:5015:17
      at C:\test\rfg-api\node_modules\async\dist\async.js:339:31
      at C:\test\rfg-api\node_modules\async\dist\async.js:847:20
      at decodeData (C:\test\rfg-api\node_modules\metaparser\index.js:30:17)
      at C:\test\rfg-api\node_modules\metaparser\index.js:37:17
      at nextTask (C:\test\rfg-api\node_modules\async\dist\async.js:5021:18)
      at Object.waterfall (C:\test\rfg-api\node_modules\async\dist\async.js:5024:9)
      at module.exports (C:\test\rfg-api\node_modules\metaparser\index.js:24:15)
      at Object.exports.injectFaviconMarkups (C:\test\rfg-api\index.js:111:5)
      at Context.<anonymous> (C:\test\rfg-api\test\test.js:204:11)
      at callFnAsync (C:\test\rfg-api\node_modules\mocha\lib\runnable.js:349:8)
      at Test.Runnable.run (C:\test\rfg-api\node_modules\mocha\lib\runnable.js:301:7)
      at Runner.runTest (C:\test\rfg-api\node_modules\mocha\lib\runner.js:422:10)
      at C:\test\rfg-api\node_modules\mocha\lib\runner.js:528:12
      at next (C:\test\rfg-api\node_modules\mocha\lib\runner.js:342:14)
      at C:\test\rfg-api\node_modules\mocha\lib\runner.js:352:7
      at next (C:\test\rfg-api\node_modules\mocha\lib\runner.js:284:14)
      at Immediate.<anonymous> (C:\test\rfg-api\node_modules\mocha\lib\runner.js:320:5)



npm ERR! Test failed.  See above for more details.
```
