### ISSUE TITLE
Unable to generate favicons and Injecting markup into file with common task without any errors 😭

### ISSUE THREAD

**Issue by evijay** [RealFaviconGenerator/grunt-real-favicon#44]
with `grunt-real-favicon` 
<h3>Unable to generate favicons and Injecting markup into file with common task without any errors 😭</h3>
`["grunt build"]`

```
PS D:\xampp\htdocs\root\project> grunt build
Running "clean:build" (clean) task
>> 2 paths cleaned.

Running "less:build" (less) task
>> 1 stylesheet created.

Running "csscomb:build" (csscomb) task
>> Using default config file...


Running "postcss:build" (postcss) task
>> No source files were found.

Running "cssmin:build" (cssmin) task
>> 1 file created. 50.81 kB → 40.75 kB

Running "copy:build" (copy) task
Created 2 directories, copied 6 files

Running "realFavicon:build" (realFavicon) task
Generating "src/images/favicons/favicons.png" favicon...
Done, without errors.

Execution Time (2018-06-29 19:35:13 UTC+5:30)
loading tasks  740ms  ████████████████████████████████████████████████████████████ 48%
clean:build     56ms  █████ 4%
less:build     288ms  ████████████████████████ 19%
csscomb:build   78ms  ███████ 5%
cssmin:build   283ms  ███████████████████████ 18%
copy:build      91ms  ████████ 6%
Total 1.5s
```

<h3>But it will done finely with individually task</h3>
`["grunt realFavicon"]`

```
PS D:\xampp\htdocs\root\project> grunt realFavicon
Running "realFavicon:build" (realFavicon) task
Generating "src/images/favicons/favicons.png" favicon...OK
Injecting markup into file: dist/index.html

Done, without errors.


Execution Time (2018-06-29 19:36:38 UTC+5:30)
loading tasks      749ms  ████ 3%
realFavicon:build  23.6s  █████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 97%
Total 24.4s
```

**Comment by phbernard** [comment]
Wait, where is the error? :)

**Comment by papismurf** [comment]
I'm having a similar problem too when running:
`real-favicon inject static/faviconDescription.json static/outputDir/ templates/frontend/*.html
`

I'm getting this output:

`TypeError: Cannot read property 'html_code' of undefined
    at /usr/lib/node_modules/cli-real-favicon/real-favicon-inject.js:23:34
    at tryCatcher (/usr/lib/node_modules/cli-real-favicon/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/cli-real-favicon/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/lib/node_modules/cli-real-favicon/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/cli-real-favicon/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/lib/node_modules/cli-real-favicon/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/usr/lib/node_modules/cli-real-favicon/node_modules/bluebird/js/release/promise.js:638:18)
    at /usr/lib/node_modules/cli-real-favicon/node_modules/bluebird/js/release/nodeback.js:42:21
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
`

Is there something I have missed or done incorrectly?
